#!/usr/bin/env python

import argparse
import sys
import logging


VERSION = 'v0.1.0'

class ReStoreIt(object):
    def __init__(self, config_file):
        # Parse config file
        pass

    def run(self):
        # Start in desired mode
        logging.info('Starting re-store-it')

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('-V', '--version', action='version', version='%(prog)s ' + VERSION)
    parser.add_argument('-v', '--verbose', action='store_const', const='DEBUG', default='WARNING', help='enable verbose output')
    parser.add_argument('--log-file', dest='log_file', metavar='LOGFILE', help='specify a log file. Default: stdout')
    parser.add_argument('config_file', metavar='CONFIGFILE', help='the config file to use')

    args = parser.parse_args()

    log_level = getattr(logging, args.verbose)
    logger_config = {'level': log_level, 'format':'[%(levelname)s] - %(asctime)s - %(message)s'}

    if args.log_file:
        logger_config['filename']=args.log_file
    
    logging.basicConfig(**logger_config)

    restoreit = ReStoreIt(args.config_file)
    restoreit.run()
